### ISSUE TITLE
46.14 will not compile

### ISSUE THREAD

**Issue by chrcoluk** [HardenedBSD/hardenedBSD-stable#6] opened 2017-01-30 13:35 UTC
I cannot get world to compile using the 46.14 tagged code.

I have tried with safestack on and off and libressl on or off, I dont know if there is other flags I can try to play with in src.conf

`clang  -O2 -pipe -DHARDENEDBSD -march=ivybridge  -I/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl -DTERMIOS -DANSI_SOURCE -DOPENSSL_THREADS -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DOPENSSL_IA32_SSE2 -DAES_ASM -DBSAES_ASM -DVPAES_ASM -DECP_NISTZ256_ASM -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DMD5_ASM -DGHASH_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DWHIRLPOOL_ASM -I/usr/obj/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto -I/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl/crypto -I/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl/crypto/asn1 -I/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl/crypto/evp -I/usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl/crypto/modes -fpic -MD  -MF.depend.conf_sap.o -MTconf_sap.o -std=gnu89 -fstack-protector-strong -Wno-pointer-sign -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses  -Qunused-arguments  -c /usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto/../../../crypto/openssl/crypto/conf/conf_sap.c -o conf_sap.o
--- kerberos5/lib/libroken__L ---
ctfconvert -L VERSION -g hostent_find_fqdn.o
ERROR: ctfconvert: rc = -1 No entry found [dwarf_next_cu_header_c(61)]
--- issuid.o ---
clang  -O2 -pipe -DHARDENEDBSD -I/usr/src/hardenedbsd-11-stable-46.14/kerberos5/lib/libroken/../../../crypto/heimdal/lib/roken -I. -march=ivybridge  -DHAVE_CONFIG_H -I/usr/src/hardenedbsd-11-stable-46.14/kerberos5/lib/libroken/../../include -fpic -MD  -MF.depend.issuid.o -MTissuid.o -std=gnu99 -fstack-protector-strong    -Qunused-arguments  -c /usr/src/hardenedbsd-11-stable-46.14/kerberos5/lib/libroken/../../../crypto/heimdal/lib/roken/issuid.c -o issuid.o
--- lib/libkvm__L ---
/usr/src/hardenedbsd-11-stable-46.14/lib/libkvm/kvm.c:445:39: error: use of undeclared identifier '_PATH_DEVVMM'
            strncmp(mf, _PATH_DEVVMM, strlen(_PATH_DEVVMM)) == 0) {
                                             ^
/usr/src/hardenedbsd-11-stable-46.14/lib/libkvm/kvm.c:445:18: error: use of undeclared identifier '_PATH_DEVVMM'
            strncmp(mf, _PATH_DEVVMM, strlen(_PATH_DEVVMM)) == 0) {
                        ^
2 errors generated.
*** [kvm.o] Error code 1

make[4]: stopped in /usr/src/hardenedbsd-11-stable-46.14/lib/libkvm
1 error

make[4]: stopped in /usr/src/hardenedbsd-11-stable-46.14/lib/libkvm
*** [lib/libkvm__L] Error code 2

make[3]: stopped in /usr/src/hardenedbsd-11-stable-46.14
--- secure/lib/libcrypto__L ---
ctfconvert -L VERSION -g conf_sap.o
ERROR: ctfconvert: rc = -1 No entry found [dwarf_next_cu_header_c(61)]
A failure has been detected in another branch of the parallel make

make[4]: stopped in /usr/src/hardenedbsd-11-stable-46.14/secure/lib/libcrypto
*** [secure/lib/libcrypto__L] Error code 2

make[3]: stopped in /usr/src/hardenedbsd-11-stable-46.14
--- kerberos5/lib/libroken__L ---
ctfconvert -L VERSION -g issuid.o
ERROR: ctfconvert: rc = -1 No entry found [dwarf_next_cu_header_c(61)]
A failure has been detected in another branch of the parallel make

make[4]: stopped in /usr/src/hardenedbsd-11-stable-46.14/kerberos5/lib/libroken
*** [kerberos5/lib/libroken__L] Error code 2

make[3]: stopped in /usr/src/hardenedbsd-11-stable-46.14
--- lib/libc++__L ---
A failure has been detected in another branch of the parallel make

make[4]: stopped in /usr/src/hardenedbsd-11-stable-46.14/lib/libc++
*** [lib/libc++__L] Error code 2

make[3]: stopped in /usr/src/hardenedbsd-11-stable-46.14
4 errors

make[3]: stopped in /usr/src/hardenedbsd-11-stable-46.14
*** [libraries] Error code 2

make[2]: stopped in /usr/src/hardenedbsd-11-stable-46.14
1 error

make[2]: stopped in /usr/src/hardenedbsd-11-stable-46.14
*** [_libraries] Error code 2

make[1]: stopped in /usr/src/hardenedbsd-11-stable-46.14
1 error

make[1]: stopped in /usr/src/hardenedbsd-11-stable-46.14
*** [buildworld] Error code 2

make: stopped in /usr/src/hardenedbsd-11-stable-46.14
1 error

make: stopped in /usr/src/hardenedbsd-11-stable-46.14`

**Comment by chrcoluk** [comment] 2017-01-30 15:25
I retested compiling the master src code which is compiling fine, so seems something specific in 46.14.

**Comment by lattera** [comment] 2017-01-30 18:16
I'm unable to reproduce. Do you have anything in src.conf and/or make.conf?

**Comment by opntr** [comment] 2017-01-30 18:41
Log for ther release build: http://installer.hardenedbsd.org/logs/done/20170129104634-hardened_11_stable_master
Log for the CI build: http://jenkins.hardenedbsd.org:8180/jenkins/job/HardenedBSD-stable-11-STABLE-master-amd64/

**Comment by opntr** [comment] 2017-01-30 18:42
Try to delete the content of /usr/obj directory before the build.

**Comment by opntr** [comment] 2017-01-30 18:47
What's the build hosts version? What's in /etc/src.conf and in /etc/malloc.conf? What's the command you use to build the system? Etc, etc, ....

**Comment by chrcoluk** [comment] 2017-01-31 12:45
/etc/src.conf content

`WITHOUT_GAMES=yes
WITHOUT_I4B=yes
WITHOUT_FLOPPY=yes
WITH_CLANG_EXTRAS=yes
WITHOUT_PROFILE=yes
WITHOUT_IPFILTER=yes
WITHOUT_BLUETOOTH=yes
WITHOUT_CVS=yes
WITHOUT_IPX=yes
WITHOUT_PPP=yes
WITHOUT_WIRELESS=yes`

/etc/make.conf - note I have tested with make.conf deleted.

MODULES_OVERRIDE=accf_dns accf_data accf_http acl_posix1e aesni ahci cc coretemp cpuctl cpufreq crypto cryptodev ctl dtrace fdc fdescfs filemon fuse geom ipmi ipw kbdmux linprocfs linsysfs linux linux64 linux_common linuxkpi mac_biba mac_bsdextended mac_ifoff mac_lomac mac_mls mac_none mac_partition mac_portacl mac_seeotheruids mac_stub mac_test mem netgraph netmap nfscommon nfscl nfscommon nfsd nfslock nfslockd nfssvc nullfs nvram nvme opensolaris padlock padlock_rng pccard pf pflog pfsync procfs pseudofs random_fortuna random_other random_yarrow rc4 rdrand_rng syscons sysvipc tmpfs zfs zlib if_bridge bridgestp`
DEFAULT_VERSIONS= perl5=5.24 mysql=56p bdb=5 python=2.7 python2=2.7 python3=3.4 tcltk=8.6 ruby=2.2 ghostscript=9
WITHOUT="X11 XPM X DEBUG DOCS
OPTIONS_SET= INET6 IPV6 THREADS ICONV OPTIMIZED_CFLAGS OPENSSL_PORT ICONV_PORT
OPTIONS_UNSET= X11 XPM X DEBUG DOCS"
`

/etc/malloc.conf doesnt exist.

to build is as follows.

rm -rf /usr/obj/*
make -j4 buildworld

**Comment by chrcoluk** [comment] 2017-01-31 12:53
I see your test build was done on master branch, I already said master is working fine.  Please test 46.14 :)

Also incase I used the wrong command and possibly have incomplete src files this is how I fetched 46.14 as git doesnt seem very friendly to fetch specific versions.

'git clone --single-branch --branch 'HardenedBSD-11-STABLE-v46.14' https://github.com/hardenedbsd/hardenedbsd-stable/ hardenedbsd-11-stable-46.14'

**Comment by chrcoluk** [comment] 2017-01-31 13:06
I fetched https://github.com/HardenedBSD/hardenedBSD-stable/archive/hardenedbsd-11-stable-20170129-1.tar.gz and then untarballed it to see if was an issue with how I grabbed the code but its failing in the same place still. :(

**Comment by chrcoluk** [comment] 2017-01-31 18:19
The master-libressl fails in the same place, and will not build either.

**Comment by chrcoluk** [comment] 2017-01-31 18:25
on the broken code that compiles line 445 of kvm.c is like this

    if (strncmp(mf, _PATH_FWMEM, strlen(_PATH_FWMEM)) == 0 ||
        strncmp(mf, _PATH_DEVVMM, strlen(_PATH_DEVVMM)) == 0) {

Whilst on the master code that compailes the section of code is like this, note the missing broken DEVVMM.

    if (strncmp(mf, _PATH_FWMEM, strlen(_PATH_FWMEM)) == 0)

**Comment by opntr** [comment] 2017-01-31 18:35
The info about the build host is still missing from this bugreport. The two links above builds a release exactly from the mentioned tag, and it does with the official two way build. First they bootstrap itself from the releasable version, and then builds the release. The jenkins instance just verifies that the release is buildable.

**Comment by opntr** [comment] 2017-01-31 18:36
From other part, before I published this version, I have build it at least 6 times due changes in the release script (the changes only affected or installer site's internal layout).

**Comment by lattera** [comment] 2017-01-31 18:41
I'll take a look at this. The key to this issue is figuring out which of those WITHOUT flags in src.conf causes the breakage. I'd imagine this is a problem from upstream FreeBSD (I've seen this type of problem before in FreeBSD). If it's not HardenedBSD-specific (which is what I suspect), I'll close this ticket and open one upstream to FreeBSD.

**Comment by opntr** [comment] 2017-01-31 18:59
This is a freshly pulled version from hardenedBSD-stable branch:

~~~
op@opn hardenedBSD-stable.git> git branch | awk '/\*/{print}'
* hardened/11-stable/master
op@opn hardenedBSD-stable.git> git grep _PATH_DEVVMM
include/paths.h:#define _PATH_DEVVMM    "/dev/vmm/"
lib/libkvm/kvm.c:           strncmp(mf, _PATH_DEVVMM, strlen(_PATH_DEVVMM)) == 0) {
op@opn hardenedBSD-stable.git> git tag --points-at HEAD
HardenedBSD-11-STABLE-v46.14
hardenedbsd-11-stable-20170129-1
~~~

**Comment by opntr** [comment] 2017-01-31 19:02
~~~
op@opn hardenedBSD-stable.git> git diff HardenedBSD-11-STABLE-v46.14..HEAD
op@opn hardenedBSD-stable.git> git diff HardenedBSD-11-STABLE-v46.14..hardened/11-stable/master
op@opn hardenedBSD-stable.git> git diff HEAD..hardened/11-stable/master
op@opn hardenedBSD-stable.git>
~~~

**Comment by opntr** [comment] 2017-01-31 19:03
And this is when I clone from the HardenedBSD-11-STABLE-v46.14 with the command you provide:

~~~
root@h12 hardenedbsd-11-stable-46.14# git remote -v
origin  https://github.com/hardenedbsd/hardenedbsd-stable/ (fetch)
origin  https://github.com/hardenedbsd/hardenedbsd-stable/ (push)
root@h12 hardenedbsd-11-stable-46.14# git tag --points-at HEAD
HardenedBSD-11-STABLE-v46.14
hardenedbsd-11-stable-20170129-1
root@h12 hardenedbsd-11-stable-46.14# git grep _PATH_DEVVMM
include/paths.h:#define _PATH_DEVVMM    "/dev/vmm/"
lib/libkvm/kvm.c:           strncmp(mf, _PATH_DEVVMM, strlen(_PATH_DEVVMM)) == 0) {
root@h12 hardenedbsd-11-stable-46.14#
~~~

**Comment by opntr** [comment] 2017-01-31 19:04
So, what's the version of your build host machine?

**Comment by chrcoluk** [comment] 2017-01-31 19:17
46.14 I removed as I have limited space on the VM, but I will run the git command again to fetch it and run the command above.

for 2 directories I have left.

for the master code that compiles

> root@shiva hardenedbsd-11-stable # git branch | awk '/\*/{print}'
* hardened/11-stable/master

For the master-libressl that doesnt compile

> root@shiva hardenedbsd-11-stable-libressl # git branch | awk '/\*/{print}'       
* hardened/11-stable/master-libressl

I will try again now with all WITHOUT lines removed from src.conf to see if it works.

**Comment by chrcoluk** [comment] 2017-01-31 19:20
ok starting a buildworld now without make.conf and only line in src.conf is WITH_LIBRESSL=yes

**Comment by opntr** [comment] 2017-01-31 19:54
the WITH_LIBRESSL has no effect to hardenedbsd-stable.git's hardened/11-stable/master, not to the hardenedbsd.git's hardened/11-stable/master, since the libressl code not (yet) merged back to the "master" branch.

We provide two "master" branch, one of them flavored with libressl (this is hardened/11-stable/master+libressl) and one with the stock openssl (this is hardened/11-stable/master). From the later, I periodically cut stable releases to hardenedbsd-stable repo.

**Comment by opntr** [comment] 2017-01-31 19:58
And finished my build from freshly checked out from _tag_ version:

~~~
--------------------------------------------------------------
>>> World build completed on Tue Jan 31 20:52:10 CET 2017
--------------------------------------------------------------
root has logged on pts/3 from 10.20.30.3.
root@h12 hardenedbsd-11-stable-46.14# exit
~~~

Full build log with the commands in the top: http://jenkins.hardenedbsd.org/~op/build-test-HardenedBSD-11-STABLE-v46.14.out.txt

**Comment by chrcoluk** [comment] 2017-01-31 19:58
yes I am compiling on master-libressl

I think its already got far enough that its past the point of failure so I believe lattera's hunch to be right,  I will test with each option to find the culprit.

**Comment by opntr** [comment] 2017-01-31 20:01
The master does not describes exactly the version. :)

Our branches are:
* 10-STABLE:
 * hardened/10-stable/master
* 11-STABLE:
 * hardened/11-stable/master
 * hardened/11-stable/master-libressl
* 12-CURRENT:
 * hardened/current/master

**Comment by chrcoluk** [comment] 2017-01-31 20:02
cloning now :)

root@shiva src # git clone --single-branch --branch 'HardenedBSD-11-STABLE-v46.14' https://github.com/hardenedbsd/hardenedbsd-stable/ hardenedbsd-11-stable-46.14
Cloning into 'hardenedbsd-11-stable-46.14'...

So is no confusion for rest of this thread thats what I will be testing on with each individual WITHOUT flag.

**Comment by opntr** [comment] 2017-01-31 20:05
Btw, there is a such option to git clone:

~~~
       --depth <depth>
           Create a shallow clone with a history truncated to the specified
           number of commits. Implies --single-branch unless
           --no-single-branch is given to fetch the histories near the tips of
           all branches. If you want to clone submodules shallowly, also pass
           --shallow-submodules.
~~~

**Comment by chrcoluk** [comment] 2017-02-01 18:37
All my testing passed, basically I have just managed to build world on 46.14 with my old make.conf and everything applied in src.conf, am at a loss.

The only thing I suspect now is maybe there was some issue on the previous git clone and some file's were missing.

I will retest on master-libressl, if it fails again I will then wipe the files and do a new git clone and try again.

**Comment by opntr** [comment] 2017-02-02 00:18
I closed this issue, since the libressl flavored branch is irrelevant in this repo.

**Closed** 2017-02-02 00:19 UTC
Labels: done, invalid, need info, works for me
